package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/AndrewHannigan/shed/pkg/agents"
	"github.com/AndrewHannigan/shed/pkg/config"
	"github.com/AndrewHannigan/shed/pkg/errs"
	"github.com/AndrewHannigan/shed/pkg/paths"
)

func newInitCmd() *cobra.Command {
	var (
		agentsFlag string
		noBgSync   bool
		uninstall  bool
		purge      bool
	)
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Bootstrap dirs + config; integrate with detected agents (--uninstall to reverse)",
		Long: `init creates the shed config and data directories if missing
and, in TTY mode, prompts to install shed integration into each
detected agent's config: the allowed-directory list plus SessionStart
hooks that inject the shed guide (session-context) and refresh the
store in the background (bg-sync).

Idempotent. The guide the agent sees is generated by the running binary
(see 'shed __session-context'), so it stays current across upgrades
with no re-init needed.

--uninstall reverses the agent integration instead of installing it,
removing exactly the entries init added (tracked in a sidecar state
file, so any entries you added yourself are preserved). It does NOT
remove the shed binary, and by default leaves ~/.config/shed/ and
~/.shed/ in place. Add --purge to also delete those, removing all
stored repos, workspaces, and config; --purge warns and asks for
confirmation if any workspace has uncommitted or unpushed work.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if purge && !uninstall {
				return errs.New(errs.Config, "--purge only applies with --uninstall")
			}
			if uninstall {
				return runUninstall(agentsFlag, purge)
			}
			if err := runInit(); err != nil {
				return err
			}
			return runAgentInstall(agentsFlag, noBgSync)
		},
	}
	cmd.Flags().StringVar(&agentsFlag, "agents", "auto", "agent integration: auto|all|none|<comma-separated list>")
	cmd.Flags().BoolVar(&noBgSync, "no-bg-sync", false, "skip the SessionStart bg-sync hook (keeps the session-context hook)")
	cmd.Flags().BoolVar(&uninstall, "uninstall", false, "reverse agent integration instead of installing it")
	cmd.Flags().BoolVar(&purge, "purge", false, "with --uninstall, also delete ~/.config/shed and ~/.shed (all stored repos, workspaces, and config)")
	return cmd
}

// runInit bootstraps directories and the config file. Idempotent.
func runInit() error {
	steps := []struct {
		path  string
		isDir bool
	}{
		{paths.ConfigDir(), true},
		{paths.DataDir(), true},
		{paths.ReposDir(), true},
		{paths.WorkspacesDir(), true},
		{paths.LogsDir(), true},
		{paths.ConfigFile(), false},
	}
	for _, s := range steps {
		var (
			created bool
			err     error
		)
		if s.isDir {
			created, err = ensureDir(s.path)
		} else {
			created, err = ensureConfigFile(s.path)
		}
		if err != nil {
			return errs.Wrap(errs.Config, err)
		}
		status := "exists "
		if created {
			status = "created"
		}
		fmt.Printf("%s  %s\n", status, paths.Display(s.path))
	}
	return nil
}

func runAgentInstall(flag string, noBgSync bool) error {
	if flag == "none" {
		return nil
	}
	// In non-TTY auto mode, skip silently to avoid surprise edits.
	if flag == "auto" && !stdinIsTTY() {
		fmt.Fprintln(os.Stderr, "\nskipping agent integration (non-TTY; pass --agents=all or a list to enable)")
		return nil
	}
	list, err := agents.SelectByFlag(flag)
	if err != nil {
		return errs.Wrap(errs.Config, err)
	}
	if len(list) == 0 {
		if flag == "auto" {
			fmt.Fprintln(os.Stderr, "\nno agents detected; skipping integration")
		}
		return nil
	}
	if flag == "auto" && !promptInstall(list) {
		fmt.Fprintln(os.Stderr, "skipped")
		return nil
	}

	state, err := agents.LoadState()
	if err != nil {
		return errs.Wrap(errs.Config, err)
	}
	opts := agents.InstallOptions{NoBgSync: noBgSync}
	for _, a := range list {
		fmt.Printf("\n%s:\n", a.Name())
		installed, err := a.Install(opts)
		if err != nil {
			fmt.Printf("  error: %v\n", err)
			continue
		}
		state.Agents[a.Key()] = mergeInstalled(state.Agents[a.Key()], installed)
		printInstalled(installed)
	}
	return errs.Wrap(errs.Config, agents.SaveState(state))
}

func mergeInstalled(prev, now agents.Installed) agents.Installed {
	merge := func(a, b []string) []string {
		seen := map[string]bool{}
		out := []string{}
		for _, s := range append(a, b...) {
			if !seen[s] {
				seen[s] = true
				out = append(out, s)
			}
		}
		return out
	}
	return agents.Installed{
		AddedPaths: merge(prev.AddedPaths, now.AddedPaths),
		AddedHooks: merge(prev.AddedHooks, now.AddedHooks),
		AddedFiles: merge(prev.AddedFiles, now.AddedFiles),
	}
}

func printInstalled(i agents.Installed) {
	if len(i.AddedPaths) == 0 && len(i.AddedHooks) == 0 && len(i.AddedFiles) == 0 {
		fmt.Printf("  (already up to date)\n")
		return
	}
	for _, p := range i.AddedPaths {
		fmt.Printf("  added directory: %s\n", paths.Display(p))
	}
	for _, h := range i.AddedHooks {
		fmt.Printf("  added hook:      %s\n", h)
	}
	for _, f := range i.AddedFiles {
		fmt.Printf("  added plugin:    %s\n", paths.Display(f))
	}
}

func promptInstall(list []agents.Agent) bool {
	names := []string{}
	for _, a := range list {
		names = append(names, a.Name())
	}
	fmt.Fprintf(os.Stderr, "\nDetected agents: %s\n", strings.Join(names, ", "))
	fmt.Fprint(os.Stderr, "Install shed integration for these? [Y/n] ")
	r := bufio.NewReader(os.Stdin)
	line, _ := r.ReadString('\n')
	line = strings.TrimSpace(strings.ToLower(line))
	return line == "" || line == "y" || line == "yes"
}

func stdinIsTTY() bool {
	s, err := os.Stdin.Stat()
	return err == nil && (s.Mode()&os.ModeCharDevice) != 0
}

func ensureDir(p string) (created bool, err error) {
	if _, err := os.Stat(p); err == nil {
		return false, nil
	} else if !os.IsNotExist(err) {
		return false, err
	}
	if err := os.MkdirAll(p, 0755); err != nil {
		return false, err
	}
	return true, nil
}

func ensureConfigFile(p string) (created bool, err error) {
	if _, err := os.Stat(p); err == nil {
		return false, nil
	} else if !os.IsNotExist(err) {
		return false, err
	}
	if err := os.WriteFile(p, config.EmptyTemplate(), 0644); err != nil {
		return false, err
	}
	return true, nil
}
