package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/AndrewHannigan/repocache/pkg/errs"
)

func newHelpCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "help [topic]",
		Short: "Long-form docs on a command or concept",
		Long: `help prints prose documentation for a command or concept.
With no topic, prints an overview.

Topics: ` + strings.Join(topicList(), ", "),
		Args:               cobra.MaximumNArgs(1),
		DisableFlagParsing: false,
		RunE: func(cmd *cobra.Command, args []string) error {
			topic := "overview"
			if len(args) == 1 {
				topic = args[0]
			}
			return runHelp(topic)
		},
	}
}

func runHelp(topic string) error {
	text, ok := helpTopics[topic]
	if !ok {
		return errs.New(errs.NotFound, "unknown topic %q (try: %s)",
			topic, strings.Join(topicList(), ", "))
	}
	fmt.Print(text)
	return nil
}

func topicList() []string {
	keys := make([]string, 0, len(helpTopics))
	for k := range helpTopics {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

var helpTopics = map[string]string{

	"overview": `repocache — git repo management for terminal coding agents

The whole loop:

    repocache init                          # one-time: dirs + agent integration
    repocache add <git-url>                 # add a repo (or a user/org) to the library
    repocache sync                          # fetch + chmod a-w on the working tree
    repocache workspace new <repo> <branch>            # prints path to a writable clone
    # ... edit there, commit, push ...
    repocache workspace rm <repo> <branch>  # tear down

Commands:
  init          bootstrap + integrate with detected agents
  uninstall     reverse agent integration (--purge also deletes data + config)
  add           add a repo (or a whole user/org) to the library
  ls            list tracked repos and owners
  rm            remove a tracked repo or owner
  sync          fetch tracked repos and re-apply read-only chmod
  workspace     {new,ls,path,rm} of writable workspaces
  gc            delete workspaces whose branch has a merged PR
  help <topic>  long-form docs

Topics: agents, auth, concepts, gc, init, library, locking, owner, sync, workspace
`,

	"concepts": `Concepts

Library
  The set of repos you've told repocache to track. Stored in
  ~/.config/repocache/config.toml. Edit via 'repocache add/rm/ls'.

Cache repo
  A full clone of one library repo, kept on disk with its working tree
  marked read-only (chmod -R a-w). One per library entry. Lives under
  ~/.repocache/repos/<host>/<owner>/<repo>/.

Workspace
  An editable clone of a cache repo, derived via 'git clone --reference'.
  Identified by (repo, branch). Multiple workspaces may exist per cache
  repo, even on the same branch. Lives under
  ~/.repocache/workspaces/<host>/<owner>/<repo>/<branch>/.

Agent integration
  Per-agent edits that 'repocache init' makes so each terminal agent:
  (a) knows repocache exists (via a SessionStart hook that injects the
  repocache guide into the session context), (b) has filesystem access
  to the cache and workspaces directories, (c) refreshes the cache in
  the background at session start.
`,

	"init": `init — bootstrap + agent integration

Creates the repocache config and data directories if missing, writes an
empty config file, and in TTY mode prompts to install integration for
each detected agent.

Flags:
  --agents=auto|all|none|<list>   which agents to integrate (default auto)
  --no-bg-sync                    skip the SessionStart bg-sync hook
                                  (keeps the session-context hook)

Modes:
  auto (TTY)    detect installed agents and prompt to install
  auto (non-TTY) skip agent integration silently (scripted use)
  all           install for every supported agent, even undetected ones
  none          skip agent integration entirely
  <list>        comma-separated agent keys, e.g. claude,cursor

Re-running init is safe: directory and hook entries are idempotent. The
guide the agent sees is generated by the binary at session start (see
'repocache __session-context'), so it stays current across upgrades with
no re-init needed.

To reverse only the agent integration (without removing your config or
cache), use 'repocache uninstall'.
`,

	"uninstall": `uninstall — reverse agent integration

Removes the entries 'repocache init' added to each agent's config:
  - the allowed-directory entries in settings.json / config.toml
  - the SessionStart hooks (session-context and bg-sync)

It also cleans up the legacy @REPOCACHE.md import line and on-disk doc
that older repocache versions installed.

Uses a sidecar state file
(~/.repocache/agents.state.json) to know exactly which
entries are repocache's, so user-added entries in the same files are
preserved.

By default this does NOT delete ~/.config/repocache/ or
~/.repocache/.

Pass --purge to also delete both directories, removing all cached
repos, workspaces, and config. If any workspace has uncommitted or
unpushed work, --purge lists those workspaces and asks for
confirmation before deleting (and refuses when stdin is not a TTY).
`,

	"library": `library — manage tracked repos and owners

  repocache add <repo> [--name <n>] [--owner|--repo]
    Add a repo to the library. <repo> may be a full git URL or GitHub
    shorthand: a bare 'owner/repo' or 'owner' is expanded against
    github.com, so 'repocache add octocat/Hello-World' works.
    Name defaults to <host>/<owner>/<repo> derived from the URL. --name
    overrides. Fetches the new repo right away (runs a scoped 'sync').
    Exit 3 if the name already exists.

    If <repo> is a bare user/org (one path segment, e.g. octocat or
    https://github.com/octocat) it is tracked as an owner instead;
    sync then discovers and adds that owner's repos. Detection is automatic;
    --owner / --repo force it. See 'repocache help owner'.

  repocache rm <name> [--force]
    Remove a repo completely: the config entry, the cache on disk, and
    every workspace derived from it. Refuses if any workspace has
    uncommitted or unpushed changes unless --force is given. Restores
    write permissions on the read-only cache tree automatically.

    If <name> is an owner, removes the owner entry and every repo it
    auto-added (with the same safety checks).

  repocache ls [--json]
    Show tracked owners, then repos with last sync and the owner that
    auto-added each (if any).
`,

	"owner": `owner — track a whole user or org

Add an owner with 'repocache add <owner-url>' (a URL with a single
path segment, e.g. https://github.com/octocat). On every sync,
repocache lists that owner's repos and adds any new ones to the library
automatically, so repos created upstream after you start tracking are
picked up and fetched without another 'add'. This also happens in
the background at each agent session start (see 'repocache help sync').

Discovery uses the 'gh' CLI — repocache's only dependency beyond 'git',
and only for discovery. Once a repo has been discovered it is an ordinary
library entry that syncs with plain 'git'. So if 'gh' is missing or not
authenticated, repocache degrades gracefully: it warns and skips
discovery, but already-known repos still sync.

By default an owner pulls its non-fork, non-archived repos (including
private ones you can access). Tune per owner in config.toml:

  [[owner]]
  url = "https://github.com/octocat"
  include_forks = false       # default
  include_archived = false    # default
  visibility = "all"          # all|public|private

Reconciliation is additive: repos that disappear upstream are left in
place (so a workspace with unpushed work is never deleted out from under
you). Remove them yourself with 'repocache rm <name>', or drop the
whole owner with 'repocache rm <owner>'.
`,

	"sync": `sync — fetch repos and re-apply read-only chmod

  repocache sync [<name>...] [--if-older-than <dur>] [--jobs N] [--json]

Before fetching, sync expands any tracked owners in scope: it lists each
owner's repos via 'gh' and adds new ones to the library, then fetches them
in the same pass (a brand-new repo has no cache, so it is cloned). Naming
an owner syncs all of its repos. If 'gh' is unavailable, discovery is
skipped with a warning and already-known repos still sync. See
'repocache help owner'.

Behavior per repo:
  1. Clone if missing (with gc.auto=0).
  2. Acquire exclusive flock on the cache repo (5 min timeout).
  3. If --if-older-than D and last_sync_at is fresher than D, skip.
  4. chmod -R u+w on the working tree (excluding .git/) so checkout works.
  5. git fetch --all --prune --tags
  6. git checkout --detach --force origin/HEAD (skipped if the remote is
     empty; GIT_LFS_SKIP_SMUDGE=1 keeps LFS blobs out of the mirror).
  7. chmod -R a-w on the working tree (excluding .git/) — read-only again.
  8. Write .git/repocache.meta with new last_sync_at.

Parallelism via --jobs (default 4). Per-repo locks serialize concurrent
syncs of the same repo. Aggregate exit:
  5 if any per-repo lock acquisition timed out
  6 if any git fetch/clone failed
  else 0

The background variant ('repocache __bg-sync', invoked by Claude's
SessionStart hook) wraps this with a global flock so multiple sessions
don't stampede.
`,

	"workspace": `workspace — manage writable workspaces

A workspace is a git clone created with --reference against the cache,
sharing object storage but with independent refs. Edits happen here.

  repocache workspace new <repo> <branch> [--base <branch>]
    Syncs the repo first (cloning it into the cache if needed), so the
    workspace forks from up-to-date code; if the sync fails but a cache
    exists, it warns and uses that. Then clones --reference into
    ~/.repocache/workspaces/.../<branch>/. If <branch> exists on origin,
    check it out. Otherwise create it off <base> (or origin/HEAD). Prints
    the absolute workspace path on stdout; make changes there, then commit
    and push.

  repocache workspace ls [--json]
    Every workspace with repo, branch, dirty state, unpushed-commit count,
    when the cache repo was last synced, and workspace directory age.

  repocache workspace path <repo> <branch>
    Print absolute workspace path. Exit 2 if missing.

  repocache workspace rm <repo> <branch> [--force]
    Delete workspace dir. Refuses with exit 4 if dirty or unpushed
    unless --force.

The workspace's origin remote points at the upstream URL, not the cache,
so 'git push' works normally. New branches have no upstream until your
first 'git push -u origin <branch>'.

To bulk-clean workspaces whose work has already landed, see 'repocache help gc'.
`,

	"gc": `gc — delete workspaces whose branch has a merged PR

  repocache gc [--dry-run] [--force]
    Delete every workspace whose branch has a merged pull request (asks
    GitHub via the gh CLI), reclaiming the ones whose work has already
    landed. Skips workspaces with uncommitted or unpushed changes so local
    work is never lost; pass --force to remove them anyway. --dry-run
    previews without deleting.

gc is entirely gh-driven, so gh must be installed and authenticated; it
fails fast rather than degrade when gh can't report merge status.
`,

	"agents": `agents — terminal coding agent integration

Supported (auto-detected by config-dir presence):

  claude       ~/.claude/             — Claude Code
  codex        ~/.codex/              — OpenAI's Codex CLI
  cursor       ~/.cursor/             — Cursor's CLI agent (cursor-agent)
  opencode     ~/.config/opencode/    — opencode

For claude and codex, 'repocache init' writes (idempotently, recorded in a
sidecar state file so 'uninstall' can reverse precisely):

  1. The cache + workspaces dirs in the allowed-filesystem-paths
     setting (additionalDirectories / writable_roots)
  2. A SessionStart hook running 'repocache __session-context --agent
     <key>', which injects the repocache guide into the session context.
     --agent selects the output shape that agent expects (the content is
     the same for all). The text is generated by the binary, so it never
     drifts after an upgrade.
  3. A SessionStart hook running 'repocache __bg-sync', which refreshes
     the cache in the background (skip with --no-bg-sync).

cursor is also a SessionStart-hook agent, but its hooks live in
~/.cursor/hooks.json under 'hooks.sessionStart' — a flatter, camelCase
shape than Claude/Codex. 'init' adds the same two hooks there (session-
context + bg-sync); --agent cursor emits a '{"additional_context":"…"}'
JSON object Cursor injects into the conversation. Cursor has no path
allowlist (the chmod a-w on repos/ enforces read-only), so no paths are
registered. A hand-rolled ~/.cursor/plugins/local/repocache plugin, if
present, is removed so the guide isn't injected twice.

opencode has no SessionStart hook or path allowlist, so 'init' instead
drops a plugin at ~/.config/opencode/plugin/repocache.js. It runs
'repocache __bg-sync' at startup and injects the guide ('repocache
__session-context --agent opencode', the raw body) into the model's
system prompt. 'uninstall' deletes the file.
`,

	"auth": `auth — repocache delegates to git

Repocache does not manage credentials. Every git operation defers to
whatever 'git clone <url>' already works with in your shell:

  HTTPS  — credential helper ('gh auth setup-git',
           'git-credential-manager', OS keychain helpers)
  SSH    — your ssh-agent for git@github.com:... URLs

If 'git clone <url>' works in your shell, repocache works. If it
doesn't, sync exits 6 with the underlying git error.
`,

	"locking": `locking — deadlock-free by design

Three lock scopes:

  global bg-sync  ~/.repocache/.bg-sync.lock
                  exclusive, non-blocking. Held only by __bg-sync workers.

  config          ~/.config/repocache/.lock
                  exclusive, 2s timeout. Held briefly for config edits
                  (add/rm).

  per-cache-repo  <cache>/.git/repocache.lock
                  exclusive (5min timeout) for sync, shared (2s timeout)
                  for workspace new.

Fixed acquisition order: bg-sync → config → per-repo. No code path
acquires in reverse. flock auto-releases on process exit (including
SIGKILL).

The read-only enforcement (chmod -R a-w on the cache tree) excludes
.git/, so the lockfile and metadata sidecar remain writable. Sync's
first action after acquiring its lock is 'chmod -R u+w' to re-enable
write before checkout.

The chmod is a UX gotcha for cleanup: 'rm -rf ~/.repocache/
repos/<name>' will fail. Run 'chmod -R u+w' first.

See SPEC §7.1 for the full deadlock-freedom argument.
`,
}
